### ISSUE TITLE
Summary page is out of date

### ISSUE THREAD

**Issue by djcarter85** [paulbulman/Parking#19]
Currently the summary page on github pages is out of date. There is a day with interruptions whereas in the real live system there are no interruptions.

I suspect the updater has fallen over ...

**Comment by paulbulman** [comment]
Turning it off and on again fixed it, but it would be nice to have some (a) monitoring and (b) logging to be able to figure out what might have happened...

**Comment by paulbulman** [comment]
Turning it off and on again fixed it in this particular case. I suspect a network glitch etc. caused an exception, which got swallowed because it was on a System.Timers.Timer thread, but prevented the timer from restarting. Tweak made to guard against this particular issue in future, and issues created for better monitoring/logging.
